import os
from typing import Dict, Any
from pathlib import Path
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from app.core.config import settings

class ReportExporter:
    """
    Exporters for Athena Executive Reports:
    Supports Markdown, HTML, and high-fidelity PDF documents.
    """

    @staticmethod
    def to_markdown(report: Dict[str, Any]) -> str:
        md = []
        md.append(f"# {report.get('title', 'Athena Executive Report')}")
        if report.get('subtitle'):
            md.append(f"*{report.get('subtitle')}*\n")
        md.append(f"**Period:** {report.get('date_range', 'N/A')}")
        md.append(f"**Generated by Athena AI Data Analyst** on {report.get('created_at', '')}\n")
        md.append("---\n")

        # Key Metrics
        if report.get("key_metrics"):
            md.append("## Key Performance Metrics")
            for km in report["key_metrics"]:
                md.append(f"- **{km['label']}:** {km['value']} ({km['change']})")
            md.append("\n---\n")

        # Sections
        for sec in report.get("sections", []):
            md.append(f"## {sec.get('title', '')}")
            md.append(f"{sec.get('content', '')}\n")
            if sec.get("table"):
                tbl = sec["table"]
                cols = tbl.get("columns", [])
                md.append("| " + " | ".join(cols) + " |")
                md.append("| " + " | ".join(["---"] * len(cols)) + " |")
                for row in tbl.get("rows", []):
                    md.append("| " + " | ".join(str(cell) for cell in row) + " |")
                md.append("\n")

        # Risks & Anomalies
        if report.get("risks_and_anomalies"):
            md.append("## Major Risks & Operational Anomalies")
            for r in report["risks_and_anomalies"]:
                md.append(f"- **[{r['impact']} Impact] {r['risk']}**: {r['mitigation']}")
            md.append("\n")

        # Recommended Actions
        if report.get("recommended_actions"):
            md.append("## Recommended Strategic Actions")
            for i, act in enumerate(report["recommended_actions"], 1):
                md.append(f"{i}. {act}")
            md.append("\n")

        # Methodology & Limitations
        if report.get("methodology_and_limitations"):
            md.append("## Methodology & Limitations")
            for lim in report["methodology_and_limitations"]:
                md.append(f"- {lim}")
            md.append("\n")

        return "\n".join(md)

    @staticmethod
    def to_html(report: Dict[str, Any]) -> str:
        md_text = ReportExporter.to_markdown(report)
        # Clean HTML presentation
        html = f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>{report.get('title')}</title>
<style>
body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; color: #1e293b; max-width: 900px; margin: 40px auto; padding: 0 20px; }}
h1 {{ color: #0f172a; border-bottom: 2px solid #e2e8f0; padding-bottom: 8px; }}
h2 {{ color: #1e293b; margin-top: 28px; }}
table {{ width: 100%; border-collapse: collapse; margin: 20px 0; }}
th, td {{ border: 1px solid #cbd5e1; padding: 10px 14px; text-align: left; }}
th {{ background-color: #f1f5f9; font-weight: 600; }}
.badge {{ display: inline-block; padding: 4px 8px; border-radius: 4px; font-size: 12px; font-weight: bold; background: #e2e8f0; }}
.metric-grid {{ display: grid; grid-template-columns: repeat(3, 1fr); gap: 16px; margin: 20px 0; }}
.metric-card {{ background: #f8fafc; border: 1px solid #e2e8f0; padding: 16px; border-radius: 8px; }}
.metric-val {{ font-size: 24px; font-weight: bold; color: #0f172a; }}
.metric-lbl {{ font-size: 13px; color: #64748b; }}
</style>
</head>
<body>
<h1>{report.get('title')}</h1>
<p style="color: #64748b; font-size: 16px;">{report.get('subtitle', '')}</p>
<p><strong>Period:</strong> {report.get('date_range')} &bull; <strong>Generated by Athena AI Analyst</strong></p>

<div class="metric-grid">
"""
        for km in report.get("key_metrics", []):
            html += f"""<div class="metric-card">
<div class="metric-lbl">{km['label']}</div>
<div class="metric-val">{km['value']}</div>
<div style="font-size: 12px; color: {'#dc2626' if '-' in km['change'] else '#16a34a'};">{km['change']}</div>
</div>"""

        html += "</div>\n"

        for sec in report.get("sections", []):
            html += f"<h2>{sec.get('title')}</h2>\n<p>{sec.get('content')}</p>\n"
            if sec.get("table"):
                html += "<table><thead><tr>"
                for col in sec["table"].get("columns", []):
                    html += f"<th>{col}</th>"
                html += "</tr></thead><tbody>"
                for row in sec["table"].get("rows", []):
                    html += "<tr>" + "".join(f"<td>{cell}</td>" for cell in row) + "</tr>"
                html += "</tbody></table>\n"

        html += "<h2>Recommended Actions</h2><ul>"
        for act in report.get("recommended_actions", []):
            html += f"<li>{act}</li>"
        html += "</ul></body></html>"
        return html

    @staticmethod
    def to_pdf(report: Dict[str, Any], output_path: str) -> str:
        """Generates a professional corporate PDF report via ReportLab."""
        doc = SimpleDocTemplate(output_path, pagesize=letter, rightMargin=40, leftMargin=40, topMargin=40, bottomMargin=40)
        styles = getSampleStyleSheet()
        story = []

        title_style = ParagraphStyle(
            'ReportTitle',
            parent=styles['Heading1'],
            fontSize=22,
            leading=26,
            textColor=colors.HexColor('#0f172a'),
            spaceAfter=6
        )
        sub_style = ParagraphStyle(
            'ReportSub',
            parent=styles['Normal'],
            fontSize=11,
            leading=14,
            textColor=colors.HexColor('#64748b'),
            spaceAfter=15
        )
        h2_style = ParagraphStyle(
            'ReportH2',
            parent=styles['Heading2'],
            fontSize=14,
            leading=18,
            textColor=colors.HexColor('#1e293b'),
            spaceBefore=14,
            spaceAfter=8
        )
        body_style = ParagraphStyle(
            'ReportBody',
            parent=styles['Normal'],
            fontSize=10,
            leading=14,
            textColor=colors.HexColor('#334155'),
            spaceAfter=8
        )

        story.append(Paragraph(report.get('title', 'Athena Executive Report'), title_style))
        if report.get('subtitle'):
            story.append(Paragraph(report.get('subtitle'), sub_style))
        story.append(Paragraph(f"<b>Period:</b> {report.get('date_range', '')} &nbsp;|&nbsp; <b>Athena Verified Analysis</b>", sub_style))
        story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#cbd5e1'), spaceBefore=5, spaceAfter=15))

        # Executive Sections
        for sec in report.get("sections", []):
            story.append(Paragraph(sec.get("title", ""), h2_style))
            story.append(Paragraph(sec.get("content", ""), body_style))
            if sec.get("table"):
                tbl_data = [sec["table"].get("columns", [])] + sec["table"].get("rows", [])
                t = Table(tbl_data, colWidths=[130, 85, 85, 85, 120])
                t.setStyle(TableStyle([
                    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#f1f5f9')),
                    ('TEXTCOLOR', (0, 0), (-1, -1), colors.HexColor('#1e293b')),
                    ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                    ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                    ('FONTSIZE', (0, 0), (-1, -1), 9),
                    ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
                    ('TOPPADDING', (0, 0), (-1, -1), 5),
                    ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#cbd5e1')),
                ]))
                story.append(t)
                story.append(Spacer(1, 10))

        story.append(Spacer(1, 15))
        doc.build(story)
        return output_path
